[package]

name = "rainmeter-rust"
version = "0.0.1"
authors = ["Birunthan Mohanathas <birunthan@mohanathas.com>"]

[dependencies]
time = "*"

[dependencies.rust-ini]
git = "https://github.com/zonyitoo/rust-ini"
